### ISSUE TITLE
Vorschüsse

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#106]
Bemerkungsfeld hinzufügen, aktiv inaktiv button, gerechnet und ausgebucht wird händisch

In der Auszahlungsübersicht unten 
Vorschüsse gesamt ausrechnen ( aktive ) und anzeigen

**Comment by TimUntersberger** [comment]
Anzeigen so wie jetzt gerade? oder unten gesammelt?

**Comment by pklinser** [comment]
Einfach unten gesammelt.
Wie wirds jetzt angezeigt?
Vor 1h war noch nix da?
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.

**Comment by TimUntersberger** [comment]
Wenn alle statt nicht bezahlte im dropdown, dann werden auch Vorschüsse angezeigt. Die werden wie Bezahlungen angezeigt nur mit negativen Wert.

**Comment by TimUntersberger** [comment]
Sollen die dann in einer eigenen Tabelle angezeigt werden oder ganz hinten bei den Bezahlungen?

**Comment by pklinser** [comment]
Einfach in der Übersicht.
Uwe setzt die dann auf inaktiv wenn Provisionen bezahlt werden, aber dann brauchen wir nicht rechnen, das hört sich eh auf mit den vorschüsse.
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.

**Comment by TimUntersberger** [comment]
Ich hänge die Vorschüsse jetzt hinten dran oda soll ich sie auch nach dem Datum sortieren?.

**Comment by TimUntersberger** [comment]
Damit mein ich sortiert zusammen mit den bezahlungen.

**Comment by TimUntersberger** [comment]
sortiers doch mit. Ist so logischer
