### ISSUE TITLE
Tippgeber login darf seine Subtippgeber schon sehen

### ISSUE THREAD

**Issue by TimUntersberger** [bizznet/Sportwetten#111]

**Comment by TimUntersberger** [comment]
Wo sehen?

**Comment by pklinser** [comment]
Auszahlung, verträge
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
