### ISSUE TITLE
auszahlungsübersicht

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#115]
michael leidinger 
2x in der auszahlung 

20.08.2019	Michael Leidinger	40,500.00 €	Bar	Nein	Michael Leidinger		Laufzeitende			more_vert
20.08.2019	Michael Leidinger	40,500.00 €	Bar	Nein	Michael Leidinger		Laufzeitende

**Comment by TimUntersberger** [comment]
NOTE: Database had a dead payment. (Meaning not a single contract cared about it)

**Comment by pklinser** [comment]
Was heisst das?
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
