### ISSUE TITLE
News Bereich

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#117]
Auf der Startseite einen News Bereich ( damits nicht so leer ist ) einrichten.

eingabe einfach heutiges Datum und Memofeld.
anzeigen dann einfach nach datum absteigend sortiert auf der startseite

**Comment by TimUntersberger** [comment]
Is des afoch a filler? Des klingt a bissi nutzlos. Soi i afoch die Homepage entfernen bzw Contracts ois default nehmen?

**Comment by pklinser** [comment]
Na, er braucht des für Ankündigungen oder Änderungen damit alle sehen
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
