### ISSUE TITLE
emailversand

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#118]
wie schon erwähnt wäre es sinnvoll, wenn man eine meldung bekommt, nachricht versendet, wenn OK.

Wenn Mailversand schon erfolgt ist, wäre es schön, wenn das mailicon andere Farbe bekommen würde

**Comment by TimUntersberger** [comment]
Soits den automatischen email versand jetzt eigentlich noch geben?

**Comment by pklinser** [comment]
Ja, vor vertragsablauf usw.
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
