### ISSUE TITLE
Eurowert in Tabelle speichern mit eigenem Menüpunkt nur für ADMIN.

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#126]
Datum und Eurowert.
Löschmöglichkeit und Editieren mit Kennwort versehen 
neuanlage ohne kennwort

man könnte auch den wert dort lassen, aber halt beim draufklicken das ganze irgendwie implementieren. ( so pop up fenster like)
je nachdem wies leichter zu realisieren ist

**Comment by TimUntersberger** [comment]
Und du hosd in Uwe wieder gfrogt ob er es so will? Wie gesagt, er hod mir gschrieben, dass ma ned löschen können soll.

**Comment by pklinser** [comment]
lass es mal so
