### ISSUE TITLE
dropdown Kunde, Tippgeber, Subtippgeber

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#51]
hier wird überall auf den Username gegangen.

bitte zumindest im Dropdown zusätzlich Vorname, Nachname und ev. PLZ anzeigen beim auswählen.

suche dort wäre auch gut wenn auf vorname, nachname und firmenname ginge, da die username nicht jeder weis

**Comment by TimUntersberger** [comment]
- [ ] Dropdowns die etwas mit account zu tun haben den display wert von username zu name + plz
- [ ] Bei der suche firmenname inkludieren
