### ISSUE TITLE
Diagramme

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#53]
für den abschluss dann:

Umsatzübersicht in Diagrammform.

pro Jahr/Quartal/Monat
pro TIppgeber (inkl. Subtippgeber)
pro Subtippgeber
gesamt

mach ich noch diagramm in excel als vorlage

**Comment by TimUntersberger** [comment]
Machen wir glaub ich nicht mehr?

**Comment by pklinser** [comment]
Doch aber erst wenn alles andere erledigt ist
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
