### ISSUE TITLE
email an alle verschicken

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#70]
Bitte eine meldung vorschalten: Email versenden JA/Abbrechen
Oberhalb bitte mit Haken auflisten:
Greenbook
Kunde
Tippgeber
Subtippgeber
und dann bei Ja nur an die ausgewählten das mail verschicken.

Neue Emailadresse zum Verschicken bekommst noch, inkl. Zugangsdaten.

Und den Text unbedingt ändern, Vertrag mit Greenbook Sports Ltd. Nicht Bizznet

Und als text bitte:

Sehr geehrte(r) Vorname Nachname,

anbei wie vereinbart Ihr Vertrag.

Mit freundlichen Grüßen

Greenbook Sports Ltd.

**Comment by TimUntersberger** [comment]
Welche addresse is mit greenbook gmand?

**Comment by pklinser** [comment]
investors@greenbooksports.com




Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
Von: TimUntersberger <notifications@github.com>
Gesendet: Mittwoch, 17. Juli 2019 15:08
An: bizznet/Sportwetten <Sportwetten@noreply.github.com>
Cc: Peter Klinser <pklinser@bizznet.at>; Author <author@noreply.github.com>
Betreff: Re: [bizznet/Sportwetten] email an alle verschicken (#70)


Welche addresse is mit greenbook gmand?

**Comment by TimUntersberger** [comment]
wos soi der text bei dem inverstors dann sein? Do ko i jo ned a person spezifisch ansprechen oda?

**Comment by pklinser** [comment]
Na des passt schon, immer den Text den i dir gschickt hab nehmen, das ist ja nur CC an investors@greenbo....





Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
Von: TimUntersberger <notifications@github.com>
Gesendet: Mittwoch, 17. Juli 2019 15:37
An: bizznet/Sportwetten <Sportwetten@noreply.github.com>
Cc: Peter Klinser <pklinser@bizznet.at>; Author <author@noreply.github.com>
Betreff: Re: [bizznet/Sportwetten] email an alle verschicken (#70)


wos soi der text bei dem inverstors dann sein? Do ko i jo ned a person spezifisch ansprechen oda?

**Comment by TimUntersberger** [comment]
Wos is dann der vorname und nachname oda afoch so drinnen lossn?

**Comment by pklinser** [comment]
Den vom Kunden lassen
________________________________

Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
