### ISSUE TITLE
configuration für email über eine webseite machen lassen. kennwort hashen

### ISSUE THREAD

**Issue by pklinser** [bizznet/Sportwetten#79]
damit die falls sich was ändert das auch selber machen können

**Comment by TimUntersberger** [comment]
I ko des kennwort ned hashen wenn i des nocha zum email verschicken brauch 😆

**Comment by pklinser** [comment]
Kann ma des ned wenigstens verschlüsselt in der db ablegen?

Muss eh für kunden konfigurierbar sein, dh. Wir brauchen da ein fenster/menü dafür


Mit freundlichen Grüßen 
Peter Klinser
Geschäftsleitung
 BizzNet IT GmbH
+43 720 890 057 0
+43 676 841 147 100
pklinser@bizznet.at
www.bizznet.at
Michlbauernweg 12a, 4040Linz
BizzNet IT GmbH übernimmt keine Haftung für den Inhalt dieser e-Mail oder für die Folgen der alle Maßnahmen auf der Grundlage der Angaben, es sei denn, diese Angaben nachträglich schriftlich bestätigt wird. Ansichten oder Meinungen präsentiert in dieser e-Mail sind ausschließlich die des Autors und geben nicht unbedingt die des Unternehmens wieder.
Von: TimUntersberger <notifications@github.com>
Gesendet: Mittwoch, 17. Juli 2019 15:09
An: bizznet/Sportwetten <Sportwetten@noreply.github.com>
Cc: Peter Klinser <pklinser@bizznet.at>; Author <author@noreply.github.com>
Betreff: Re: [bizznet/Sportwetten] configuration für email über eine webseite machen lassen. kennwort hashen (#79)


I ko des kennwort ned hashen wenn i des nocha zum email verschicken brauch 😆

**Comment by TimUntersberger** [comment]
i werd des afoch in des config file einischreiben wos ma momentan nehmen.
